### ISSUE TITLE
chore: keyman 17.0 API changes

### ISSUE THREAD

**Issue by mcdurdin** [fcitx/fcitx5-keyman#3]
This is just a heads up to let you know that the Keyman Core API has some changes upcoming with Keyman 17.0, currently in alpha, due for stable release early next year.

Two of the changes are just simple renames with no functionality change, moving away from the "keyboardprocessor" term to "Keyman Core" (as keyboardprocessor is actually an internal part of Keyman Core):

* https://github.com/keymanapp/keyman/issues/9721
* https://github.com/keymanapp/keyman/issues/9722

The third change is more significant, and is still undergoing review and implementation. The older APIs will remain functional, albeit deprecated, so you should not need to implement any changes here before moving to the 17.0 API, apart from the find/replace renames above. However I hope it will simplify the integration with Keyman Core when you do come to it:

* https://github.com/keymanapp/keyman/issues/9720

fcitx5-keyman is the only known external consumer of the Keyman Core API, so we will probably completely remove the legacy APIs in 18.0-alpha once you have a working implementation of 9720 above (or earlier if everything falls into place in time).

Please let me know if any of these changes are going to cause undue trouble for you.

**Comment by wengxt** [comment]
@mcdurdin I think the changes makes sense. 

One minor requirement on my side specially for *nix packaging: bump so version, if ABI changed, so version should be bumped. or renaming the library.

**Comment by mcdurdin** [comment]
Thanks! 

@ermshiperete, .so versioning is your area. Can you track this req?

The ABI will be marked stable for 17.0-stable but will undergo incremental changes during the 17.0-alpha phase.

**Comment by ermshiperete** [comment]
https://github.com/keymanapp/keyman/issues/9733

**Comment by mcdurdin** [comment]
See https://github.com/keymanapp/keyman/issues/10520 for final round of API changes for 17.0, removing `km_core_state_action_items()` and `km_core_state_queue_action_items()` from the normal API (they will remain in a separate header for the interactive debugger and the Windows-only legacy Input Method eXtensions support)

**Comment by hosiet** [comment]
Debian is migrating to keyman 17.0.x. As seen from https://tracker.debian.org/pkg/keyman , the API is now provided by libkeymancore instead.

 I believe current fcitx5-keyman is not compatible with keyman 17.x. Any plan for a recent fix?
